### ISSUE TITLE
Unsuccessful with updating proposal & adding a second one

### ISSUE THREAD

**Issue by Gailogail** [ACCUConf/ACCUConf_Submission_Web_Application#52] opened 2017-09-14 11:29 UTC
I tried to register (accu@ollis.org.uk) and to submit a proposal, both seemed to work OK. I then changed my passphrase in the registration details, too, and managed to log in again successfully with the new one.

After that I tried to update my the proposal. All I got was 'Submitting login details.' appearing in red just before the title box, and the changes were not saved.

The same happened when I tried to submit a second proposal.

**Comment by russel** [comment] 2017-09-17 06:55
I added https://github.com/ACCUConf/ACCUConf_Submission_Web_Application/blob/master/tests_cfp__selenium/test_s_issue_52.py to try and simulate this case, but the tests pass.

**Comment by Gailogail** [comment] 2017-10-04 09:37
OK just now with a new registration to UPDATE a proposal. Also successfully updated my registration.

Still getting nothing but "'Submitting login details.' appearing in red when I try to submit the completed form for a second proposal. 

Chrome Version 59.0.3071.115 (Official Build) (64-bit)
Linux Mint 17 Qiana
Mug: empty - perhaps I should give it a fresh cup of really hot tea ;-)

**Comment by russel** [comment] 2017-10-04 09:51
I just took a look at the database, and your passphrase has gone, which sort of explains why it's not working. So working hypothesis: a) without the registration update, multiple submissions should work; and b) registration update of details other than the passphrase is causing the passphrase to be deleted.

**Comment by Gailogail** [comment] 2017-10-04 09:54
Oh yes, just tried logging out and it's not letting me back in now.

FWIW, I did not log out before attempting the second submission and could still view my existing proposal.

**Comment by russel** [comment] 2017-10-04 10:17
The system has a very simplistic view of "logged in" which clearly gets broken with a change of passphrase  during the session. I will try and emulate this untested situation and hopefully the test fails.

Hanging is definitely not the right thing to do, I am not sure where this is happening in the code, the request should fail and result in a pop-up dialogue reporting the failure.

**Comment by Gailogail** [comment] 2017-10-04 10:25
The only change of passphrase within the session was the creation of the new one when I registered.

**Comment by Gailogail** [comment] 2017-10-04 10:27
Did wonder if maybe my pop-up weren't working, but I do get one when I try to log in now, "User/passphrase not recognised" - which is a reasonable thing for it to say if my passphrase has disappeared from the system!

**Comment by russel** [comment] 2017-10-04 10:31
The original "Issue 52" scenario had the registration update be a change of password, but without a termination of the login session. I think it turns out this issue is going to have to split into many contributing test scenarios. I shall withdraw into a quiet bunker and get this sorted. Thanks for your efforts on this, most constructive!

**Comment by Gailogail** [comment] 2017-10-04 10:38
A quiet bunker is the best place to be at the moment :-/
Yell when you want me to see if my unintentionally malign touch breaks it.

**Comment by russel** [comment] 2017-10-05 16:00
It is believed that this pair of faults are both now fixed. If not feel free to reopen this bug report.

**Comment by Gailogail** [comment] 2017-10-06 15:44
Updates on my existing proposal are now working. But I still can't submit a second one successfully.

Can you view this video of the attempt? In theory it is visible to anyone with the link
https://bournemouth.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=ba4f4d64-12a1-4c1b-b1a2-1e580ebf00a8

**Comment by russel** [comment] 2017-10-12 13:17
It seems the "you have to login" software takes precedence over the URL. I am not sure I have a login to see it. Is there somewhere else you can drop the video?

**Comment by Gailogail** [comment] 2017-10-12 13:20
Hmm, the video permissions had reverted to requiring sign-in -
 maybe I omitted to press a wayward save button. Can you see this now?https://bournemouth.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=ba4f4d64-12a1-4c1b-b1a2-1e580ebf00a8

**Comment by russel** [comment] 2017-10-12 13:34
Sponditious. I am wondering if the problem is that the bio was only 47 characters and thus failed the >50 test and yet it got through and sent to the server which then sent back a 400 which wasn't processed properly. Clearly a bug!

**Comment by russel** [comment] 2017-10-12 14:16
I wonder if the problem is that the system thinks it has displayed a JavaScript pop-up and is waiting for you to say "I acknowledge the error". I have just been able to get something very similar to what you are seeing which indicates a bug I understand. :-) Have you got JavaScript pop-ups disabled, if so that would explain the situation, and be a form of bug for the application.

**Comment by Gailogail** [comment] 2017-10-13 09:59
If I enter too short a title/summary I get "title not valid" / "summary not valid" messages alongside those fields.
I've tried enabling pop-ups (and disabling ublock and privacy badger for good measure) but still get the same symptoms for too short a bio: no pop-up, no message alonside the field. (I do have Fresher's Flu so it's not impossible that I messed up changing my settings; but it should do something sensible anyway, so that's relevant only to diagnosis.)
I tried making the bio long enough after that; "Submitting login details." message at the top of the page and no action.
I'll make you another video nasty!

**Comment by russel** [comment] 2017-10-13 10:20
Hummm… this is all getting a bit frustrating as the Selenium tests that I believe say this should work pass, and yet there are clearly problems. Hypothesis has to be that the Selenium tests are not testing what I think they are, and the scenario you have. :-( 

I have noticed though that browsers are very prone to not loading updated JavaScript files, but just using the ones they have cached. With Firefox I have to manually flush the cache in order to get the updated JavaScript files to load. Double :-(

**Comment by Gailogail** [comment] 2017-10-13 10:37
'Clear your browser cache' seems to be the new 'have you tried turning it off and on again' ! But it hasn't made any difference in this case. (Again, unless Fresher's Flu means I didn't do it right. Not looking for sympathy, just warning you that I may be an unreliable tester at the moment!)

**Comment by russel** [comment] 2017-10-13 11:13
:-) Sadly though in this case "flushing the cache" should cause a reloading of the JavaScript file which has changed since the last video. It appears though that the problem is still there.

Something I have been failing to look at is the logs for the failing interactions. I should look back at the time you have tried things to see if there is a "wobbly" in there.

I am getting close to thinking we need to do something a bit more synchronous, i.e. me tracking the database and the web application as you are doing things so as to try and capture the exact sequence so as to make a Selenium test of exactly the sequence.

**Comment by Gailogail** [comment] 2017-10-13 11:23
We can do that this afternoon if you like. Give me a call?

**Comment by russel** [comment] 2017-10-13 12:34
Checking the logs, I think we have a chink of light in the darkness: it seems there is some weirdness associated with presenter email uniqueness. I'll see if I can write a failing test based on this hypothesis. If I don't get far quickly, I'll fix the bug first. :-[]

**Comment by russel** [comment] 2017-10-13 12:50
Ah. we have a "how come this problem didn't come up before" situation. Thanks for persisting investigating this, it highlights a Big Bug™ that is now obvious and should have been spotted previously!

**Comment by russel** [comment] 2017-10-13 13:20
One believes one has nailed the b#gger. I have updated the application on cfp.testconference.accu.org

**Comment by Gailogail** [comment] 2017-10-13 13:47
A second proposal successfully submitted! I'll try amending it too, for good measure.

Since one of my earlier tests had a short bio I tried that first. I got "Problem with form, not submitting." at the top, but no message by the bio field - unlike the behaviour for too-short titles and summaries. Less of an issue but a bit confusing. Feel free to split that off as a different buguette.

**Comment by russel** [comment] 2017-10-13 13:56
If I could get you to put that in a separate issue, I think this one has served its purpose! :-)

**Closed by russel** 2017-10-13 13:56 UTC
Labels: bug

**Comment by Gailogail** [comment] 2017-10-13 13:58
I can confirm that I can also update my newly added proposals.

Bio issue logged in issue 54
